# Используем официальный образ PostgreSQL в качестве базового
FROM postgres:17.4

# Устанавливаем locales и postgresql-client
RUN apt-get update && apt-get install -y locales locales-all -y postgresql-client

# Копируем наши конфигурационные файлы и sql
COPY psql-config/*.conf /etc/postgresql/postgresql.conf.d/
COPY psql-config/*.sql /etc/postgresql/psql-data/

# Создаем скрипт для копирования файлов из /etc/postgresql/postgresql.conf.d в папку с данными при инициализации
RUN echo "cp /etc/postgresql/postgresql.conf.d/* \$PGDATA" > /docker-entrypoint-initdb.d/psql_configs.sh

# Делаем скрипт исполняемым
RUN chmod +x /docker-entrypoint-initdb.d/psql_configs.sh

# Копируем скрипт и устанавливаем владельца ОДНОВРЕМЕННО
# (Важно: Это должно быть сделано после создания скрипта)
RUN chown postgres:postgres /docker-entrypoint-initdb.d/psql_configs.sh

# Копируем sql-скрипты для создания таблиц и его заполнения
RUN cp /etc/postgresql/psql-data/* /docker-entrypoint-initdb.d/

# Эксплицитно объявляем volume, чтобы избежать потерь данных
VOLUME /var/lib/postgresql/data
