# Используем образ линукс Alpine с версией node 14
FROM node:24-alpine3.22

# Указываем нашу рабочую директорию
WORKDIR /web-api

# Скорировать package.json и package-lock.json внутрь контейнера
COPY package*.json ./

# Устанавливаем зависимости (Retry Wrapper)
RUN set -e; \
  max=5; i=0; \
  until [ $i -ge $max ]; do \
    npm ci --prefer-offline --no-audit --progress=false && break; \
    i=$((i+1)); \
    echo "npm install failed, attempt $i/$max. sleeping $((i*5))s..."; \
    sleep $((i*5)); \
  done; \
  if [ $i -ge $max ]; then echo "npm ci failed after $max attempts" && exit 1; fi

# Копируем оставшиеся приложения в контейнер
COPY . . 

# Сборка приложения в /dist
RUN npm run build:prod

# Открыть порт в нашем контейнер
EXPOSE 8080

# Запускаем наш сервер
CMD ["npm", "start"]

VOLUME /web-api
