version: "3.9"

secrets:
  psql_root_user_pass:
    file: ./secrets/psql_root_user_pass
  redis_pass:
    file: ./secrets/redis_pass
  rm_user:
    file: ./secrets/rm_user
  rm_pass:
    file: ./secrets/rm_pass
  app_env_file:
    file: ./.env.production

services:
  web-api:
    build:
      context: .  # Директория, содержащая Dockerfile
      dockerfile: Dockerfile-Node
    container_name: "web-api"
    secrets:
      - source: app_env_file
        target: app_env_file
        mode: 0400
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db
      - rabbitmq
      - redis
    volumes:
      - app_data:/web-api
      - shared_uploads:/web-api/uploads
    networks:
      - my_network
    
  postgres-db:
    build:
      context: .  # Директория, содержащая Dockerfile
      dockerfile: Dockerfile-PG
    container_name: "postgres"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ST_c&Rsov@aya789
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_root_user_pass
      POSTGRES_DB: root_db
    secrets:
      - source: psql_root_user_pass
        target: psql_root_user_pass
        mode: 0400
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:8.6.2
    container_name: "redis"
    hostname: redis
    ports:
      - "6379:6379"
    command: [ "sh", "-c", "redis-server --requirepass $$(cat /run/secrets/redis_pass)" ]
    secrets:
      - source: redis_pass
        target: redis_pass
        mode: 0400
    volumes:
      - rs_data:/rs_data
    networks:
      - my_network
  
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    entrypoint: >
      sh -c "
      export RABBITMQ_DEFAULT_USER=\$$(cat /run/secrets/rm_user) &&
      export RABBITMQ_DEFAULT_PASS=\$$(cat /run/secrets/rm_pass) &&
      exec docker-entrypoint.sh rabbitmq-server
      "
    secrets:
      - source: rm_user
        target: rm_user
        mode: 0400
      - source: rm_pass
        target: rm_pass
        mode: 0400
    volumes:
      - rm_data:/var/lib/rabbitmq
    networks:
      - my_network

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-Nginx
    container_name: "nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/ssl
      - shared_uploads:/web-api/uploads:ro 
    networks:
      - my_network

volumes:
  db_data:
  app_data:
  rm_data:
  rs_data:
  shared_uploads:

networks:
  my_network:
